import type { Metadata } from "next";
import "./globals.css";
import Header from "@/features/Header/Header";
import Footer from "@/features/Footer/Footer";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white dark:bg-gray-950">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
